<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MaC.Core\MaC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Adapters\Mappers\Models\Services\Extensions\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
